# Generated by Django 2.1.5 on 2019-01-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0002_auto_20190129_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='blogpage',
            old_name='body',
            new_name='text',
        ),
    ]
